config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "characters#index"

  resources :characters
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/character.rb
class Character < ActiveRecord::Base
  belongs_to :user, optional: true
  validates :name, uniqueness: { scope: :user_id }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :characters
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_action :set_character, only: [:show, :edit, :update, :destroy, :verify_owner]
  before_action :verify_owner, only: [:show, :edit, :update, :destroy]

  def index
    if user_signed_in?
      @characters = current_user.characters
    else
      @users = User.all
    end
  end

  def show
  end

  def new
    @character = Character.new
  end

  def create
    @character = Character.new(character_params)

    unless current_user.blank?
      @character.user_id = current_user.id
    end

    if @character.save
      flash.notice = "#{@character.name} was created!"
      redirect_to characters_path
    else
      flash.notice = "Sorry, character could not be created!"
      render :new
    end
  end

  def edit
  end

  def update
    unless @character.blank?
      old_name = @character.name
    end

    logger.debug "debug #{@character.name} | #{params[:character][:name]}"

    if @character.name == params[:character][:name]
      flash.notice = "#{@character.name} is already the name!"
      render :edit
    else
      if @character.update_attributes(character_params)
        flash.notice = "#{old_name} was changed to #{@character.name}!"
        redirect_to characters_path
      else
        flash.notice = "Sorry, #{old_name} could not be updated!"
        render :edit
      end
    end
  end

  def destroy
    if @character.destroy
      flash.notice = "#{@character.name} was removed."
      redirect_to characters_path
    end
  end

  private

  def set_character
    if user_signed_in?
      @character = Character.find(params[:id])
    else
      flash.notice = "You need to be signed in to interact with characters."
      redirect_to characters_path
    end
  end

  def verify_owner
    if @character.user_id != current_user.id
      flash.notice = "That's not your character."
      redirect_to characters_path
    end
  end

  def character_params
    params.require(:character).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/characters/_form.html.erb
<% if @character.errors.any? %>
  <ul>
    <% @character.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @character do |f| %>
  <label for="character_name">Name</label>
  <%= f.text_field :name, autofocus: true %>
  <%= f.submit %>
<% end %>

<br>

<%= link_to "Cancel", characters_path %>

app/views/characters/edit.html.erb
<%= render partial: "form" %>

app/views/characters/index.html.erb
<% if user_signed_in? %>
  <p>You are signed in as <%= current_user.email %> | <%= link_to "Sign Out", destroy_user_session_path, method: :delete %></p>
  <h1>These Are Your Characters</h1>
  <% @characters.each do |character| %>
    <h4><%= link_to character.name, character_path(character) %>...............................<%= link_to "Remove Character", character_path(character), method: :delete %></h4>
  <% end %>
  <%= link_to "New Character", new_character_path %>
<% else %>
  <p>You need to <%= link_to "sign in", new_user_session_path %> or <%= link_to "sign up", new_user_registration_path %>.</p>
  <% unless @users.blank? %>
    <h3>Available Users:</h3>
    <ul>
      <% @users.each do |user| %>
        <li><%= link_to user.email, new_user_session_path(email: user.email) %></li>
      <% end %>
    </ul>
  <% end %>
<% end %>

app/views/characters/new.html.erb
<%= render partial: "form" %>

app/views/characters/show.html.erb
<%= @character.name %>
<br>
<br>
<%= link_to "Edit Character", edit_character_path(@character) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rpg</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
      <h5><%= flash[:notice] %></h5>
    <% end %>
    <%= yield %>
  </body>
</html>